### ISSUE TITLE
tabline style is affected when opening new tab from CtrlP

### ISSUE THREAD

**Issue by peterdutton** [DavidEGx/ctrlp-smarttabs#12]
This only happens when ctrlp-smarttabs in loaded. 

If I search for a file in CtrlP (in any view, e.g. Smart Tabs or just Files) and then open in new tab, the styling of the tabline is affected. The only way I can restore it is by quitting and restarting vim.

I am using airline for the tabline. If I open a file in a new tab using :tabe instead of CtrlP this also doesn't happen.

screenshot of before:
![before](https://cloud.githubusercontent.com/assets/942130/6025077/a2083e04-abc7-11e4-8a3d-6045d73bf2b9.png)

and after:
![after](https://cloud.githubusercontent.com/assets/942130/6025086/ab2e69e0-abc7-11e4-8ef3-e0225cc460c5.png)

**Comment by DavidEGx** [comment]
I'll have a look. Meanwhile putting

    let g:ctrlp_smarttabs_modify_tabline = 0

in your vimrc should fix it.

**Comment by DavidEGx** [comment]
...or maybe no :-/

**Comment by DavidEGx** [comment]
Fixed in 0ddd11489a5032ec09a13ef2e34fbbcce7de6f63.

If you `:BundleUpdate` or `$ git pull` everything should be fine now :)

**Comment by DavidEGx** [comment]
Thanks for report it btw!

**Comment by peterdutton** [comment]
Hi - thanks for looking at this but it still isn't fixed for me - same issue as before.

I checked for the g:ctrlp_smarttabs_modify_tabline variable by doing

:let g:ctrlp_smarttabs_modify_tabline

but it was not defined.

If there's any troubleshooting I can do to help please let me know.

Thanks again!

**Comment by peterdutton** [comment]
Sorry another update, g:ctrlp_smarttabs_modify_tabline only gets set after I open CtrlP. (it was set to 1). If I set the variable to 0 instead, the tabs work normally.

**Comment by peterdutton** [comment]
I think I have fixed it for me, when g:ctrlp_smarttabs_modify_tabline is set to 1 (although my vimscript is not very good, so apologies if this is wrong):

set a variable for the 'original' tab on startup:

let s:ctrlp_smarttabs_old_tabline = &tabline

and then restore to this on exit:

execute "set tabline=" . s:ctrlp_smarttabs_old_tabline

**Comment by DavidEGx** [comment]
Just fixed it.
hopefully...

Strangely ctrlp is calling `ctrlp#smarttabs#exit` even when smarttabs is not loaded :-\

**Comment by peterdutton** [comment]
That's fixed it - thanks!
